### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Poussinou** [joaomneto/TitanCompanion#138]
A question, just to be sure. Is this repo under LGPL v3 license or GPL v3 license?

The license file is LGPL v3, but you wrote GPL v3 in the commit description changing the license from MIT to something else.

#136

**Comment by joaomneto** [comment]
It is definitely LGPL. The commit is wrong. Thanks for noticing. I will fix it. :)

**Comment by Poussinou** [comment]
No problem ;)
