### ISSUE TITLE
ST not translated text

### ISSUE THREAD

**Issue by joaomneto** [joaomneto/TitanCompanion#58]
In gitlab by @joao.m.neto on Aug 6, 2017, 10:21

Add text translation for this screen

https://goo.gl/photos/wbeLEa1uXwjyCs3r7

**Comment by joaomneto** [comment]
In gitlab by @joao.m.neto on Aug 8, 2017, 13:01

added ~1687697 label

**Comment by joaomneto** [comment]
In gitlab by @joao.m.neto on Aug 8, 2017, 13:04

added ~1567095 label

**Comment by sebhz** [comment]
I'll handle this when I have a moment :-)

**Comment by sebhz** [comment]
Will be handled as part of issue #72. Closing this one.
