### ISSUE TITLE
Review translation for Midnight  Rogue

### ISSUE THREAD

**Issue by joaomneto** [joaomneto/TitanCompanion#66]
Hello Seb,

can you check the translation for the following Midnight Rogue strings?

I did it on my own just to finish the issue, but since i don't have a copy of the french book, I need you to review them if you don't mind.  :)
```
<!-- Midnight Rogue -->
    <string name="chosenSkills">Habilités</string>
    <string name="specialSkills">Habilités</string>
    <string name="skillList">Habilités:</string>
    <string name="selectedSkills">Habilités choisies:</string>
    <string name="skill_climb">Escalade</string>
    <string name="skill_hide">Cacher</string>
    <string name="skill_picklock">Crochetage</string>
    <string name="skill_pickpocket">Pickpocket</string>
    <string name="skill_secretsigns">Signes Secrets</string>
    <string name="skill_sneak">Furtif</string>
    <string name="skill_spot_hidden">Perception</string>
    <string name="deleteSkillQuestion">Supprimer habilité?</string>
```

[https://github.com/joaomneto/TitanCompanion/blob/master/res/values-fr/strings.xml](url)

Kind Regards

**Comment by sebhz** [comment]
No pb. Will do tonight. There are a couple of other issues I spotted regarding the French translation anyway, that also need fixing !

**Comment by sebhz** [comment]
Done. Though the translation is pretty farfetched, it is following exactly the French book translation !
