### ISSUE TITLE
Potions can be used indefinitely

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#73]
Most books rules state that each potion (skill, stamina, luck) has only two doses. Yet FFCompanion allows to use them indefinitely. Implementing a counter and deactivating the "Use XXX potion" button after 2 uses is probably easy (I did not check yet if this was already done), but we would also need to save/load the number of remaining potions when saving/loading a game.

Tested on 0.28-beta

**Comment by joaomneto** [comment]
This check was already present in the code. I must have introduced a bug somewhere. Actually, I think only TWOFM gives you 2 doses. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joaomneto** [comment]
Fixed in 0.29-beta
