### ISSUE TITLE
Problems with vehicle equipment fragment in FF

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#75]
Start a fresh FF game, then navigate to the Equipment/Enhancement Fragment.

1- the fragment name is "Vehicle Combat" - it should probably be "Vehicle Equipment" or something like this
2- there is an enhancement of value "4" in the enhancement list
3- when trying to delete the enhancement, the dialog says "Delete Note"

**Comment by joaomneto** [comment]
Fixed in 0.29-beta
