### ISSUE TITLE
Crash in POF

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#77]
Create a new Phantoms of Fear adventure, navigate to the Spell fragment. FFCompanion crashes.
BTW, do we need a spell fragment in POF ? I never played the book but reading the rules, it seems all the spells are always available.

**Comment by joaomneto** [comment]
Well, actually the only side effect for a spell is decreasing the power Stat so yeah, I think I will remove this screen. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joaomneto** [comment]
Fixed in 0.29-beta. Remove the spell screen.
