### ISSUE TITLE
Missing use potion button in WOTFM

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#80]
Create a new WOTFM adventure, chosing a potion. When adventure starts, there is no "Use potion" button.
Tested in 0.29-beta. French language. Android 6.0.1.

**Comment by joaomneto** [comment]
I cant reproduce this issue. I have found out though that if you create a fresh adventure with the same name as a previous one already saved, it won't overwrite the old one, so when loading the adventure after creation you are in fact loading the old save game. This may be the cause?

Can you try by deleting all WOTFM before testing again?

**Comment by sebhz** [comment]
I tried this, and still there is no potion button in WOTFM. Never mind, I'll investigate more, and fix this if it happens to be a real problem.

**Comment by joaomneto** [comment]
I'll do some more testing also.

**Comment by sebhz** [comment]
Can't reproduce this after recompiling the app myself. Strange...
Closing for now.
