### ISSUE TITLE
Potions seem to have only one dose

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#81]
Create a new adventure with a potion (FOD for instance). Use the potion once, the "Use potion" button becomes deactivated. It should only deactivate on the second use.
Tested on 0.29-beta. French language. Android 6.0.1.

**Comment by joaomneto** [comment]
In the English and Portuguese editions, only Warlock has 2 doses for the potion. 

In [http://fightingfantasy.wikia.com/wiki/The_Warlock_of_Firetop_Mountain_%28book%29](http://fightingfantasy.wikia.com/wiki/The_Warlock_of_Firetop_Mountain_%28book%29)

> Unique RulesEdit
> 
> Players can only eat Provisions when allowed by the instructions on a page, and only one meal > can be eaten at a time.[2] In later books players can eat at any time outside of battle. Also, while > a player has only one Potion, **it contains two doses**.

And in Forest of Doom rules, it states:

> Each bottle of potion contains enough for **_one_ measure**

It's different in the french version?

**Comment by sebhz** [comment]
Yes, French version seems different.
I just checked my French version of "Caverns of the Snow-witch" (the real book), and it states "Chaque bouteille de potion contient **deux** mesures".
I checked my PDF version of Forest of Doom, and here again, the exact same wording: two measures.

I guess we can state that FFCompanion abide by English ruling then : only one measure except for WOTFM. Supporting regional rules variant would be possible, but probably too much of a hassle. I you agree, feel free to close this issue !

**Comment by joaomneto** [comment]
I'll do it. It's just a question of adding to values.xml in different locales I believe!

**Comment by sebhz** [comment]
Well in theory one might want to play the game in English using the French rules :-).A bit farfetched I admit...


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : João Neto <notifications@github.com> 
Date : 25/08/2017  10:56  (GMT+01:00) 
À : joaomneto/TitanCompanion <TitanCompanion@noreply.github.com> 
Cc : Seb <seb@zyglute.fr>, State change <state_change@noreply.github.com> 
Objet : Re: [joaomneto/TitanCompanion] Potions seem to have only one dose
&nbsp; (#81) 

I'll do it. It's just a question of adding to values.xml in different locales I believe!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joaomneto/TitanCompanion","title":"joaomneto/TitanCompanion","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/joaomneto/TitanCompanion"}},"updates":{"snippets":[{"icon":"PERSON","message":"@joaomneto in #81: I'll do it. It's just a question of adding to values.xml in different locales I believe!"}],"action":{"name":"View Issue","url":"https://github.com/joaomneto/TitanCompanion/issues/81#issuecomment-324862163"}}}

**Comment by joaomneto** [comment]
Hmm, yeah... I'm gonna sit on this for a while...

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joaomneto** [comment]
In the activity creation I will add a pre-filled switch field enabling the user to change between one or two doses of potion. This gives the player a maximum of flexibility without letting him cheat.

**Comment by joaomneto** [comment]
I've added a pre-filled spinner to the adventure creation screen. The reader has the ability to change it from one to two doses and vice versa. It is auto filled with two doses for the french locale and only for TWOFM in the other locales
